{-
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms
    will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do
    not exceed four million, find the sum of the even-valued terms.
-}

main :: IO ()
main = print answer

-- | The upper bound set in the question.
upperbound :: Integer
upperbound = 4000000

answer :: Integer
answer = sum (filter even (takeWhile (<= upperbound) fibonacciSequence))

fibonacciSequence :: [Integer]
fibonacciSequence = [fibonacci x | x <- [1..]]

-- The seed numbers are to satisfy the definition in the question.
fibonacci :: Integer -> Integer
fibonacci 1 = 1
fibonacci 2 = 2
fibonacci n = fibonacci (n - 1) + fibonacci (n - 2)
